In [59]:
import pandas as pd
import numpy as np

In [2]:
1. #Identity matrix with 5 rows and 5 columns:
array1 = np.eye(5)
print(array1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
# 2. Diag matrix with value
array2 = np.diag([1, 2, 3, 4])
print(array2)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [25]:
#3. Create a checkerboard pattern in an array using row and col slicing
array3 = np.zeros((5,5))
#print(array3)
#array3[1::2, ::2] = 1  # Odd rows, even columns
array3[::2, 1::2] = 1  # Even rows, odd columns

print(array3)

[[0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]]


In [27]:
# Create an array of numbers from 1 to 10
array_numbers = np.arange(1, 11)

# Print the array
print("Array:", array_numbers)

# Calculate the size of the array in bytes
size_in_bytes = array_numbers.nbytes

print(f"Size of the array in bytes: {size_in_bytes} bytes")

Array: [ 1  2  3  4  5  6  7  8  9 10]
Size of the array in bytes: 40 bytes


In [28]:
# Given image snapshot
img = np.array([[200, 210, 209],
                [213, 0, 214],
                [214, 215, 217]])

# Calculate mean and median
mean_value = np.mean(img)
median_value = np.median(img)

# Print the results
print(f"Mean value of the image: {mean_value}")
print(f"Median value of the image: {median_value}")

Mean value of the image: 188.0
Median value of the image: 213.0


In [50]:
ser =pd.Series(np.arange(10, 100, 10))
print("The students Marks are:\n", ser)
print(f"Students Marks >50 are:\n {ser[ser>50]}")
print(f"Students Marks >70 are:\n {ser[ser>70]}")
print(f"Students Marks >90 are:\n {ser[ser>90]}")

The students Marks are:
 0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int32
Students Marks >50 are:
 5    60
6    70
7    80
8    90
dtype: int32
Students Marks >70 are:
 7    80
8    90
dtype: int32
Students Marks >90 are:
 Series([], dtype: int32)


In [75]:
name=np.array(['kevin','john','hari'])
age=np.array([23,21,22])
gender=np.array(['m','m','f'])
state=np.array(['TN','KL','KN'])
cgpa=np.array([9,8,7])

In [79]:
df=pd.DataFrame({'Name':name,'Age':age,'Gender':gender,'State':state,'CGPA':cgpa})
df

Name  Age Gender State  CGPA
0  kevin   23      m    TN     9
1   john   21      m    KL     8
2   hari   22      f    KN     7

In [78]:
#df=pd.DataFrame({'name':['kevin','john','hari'], 'age':[23,21,22], 'gender':['m','m','f'],'state':['TN','KL','KN'],'cgpa':[9,8,7]})
#print(df)

    name  age gender state  cgpa
0  kevin   23      m    TN     9
1   john   21      m    KL     8
2   hari   22      f    KN     7


In [86]:
#1. Filter the Age
df[['Age']]

Age
0   23
1   21
2   22

In [88]:
#2.filter age,cgpa
df[['Age','CGPA']]

Age  CGPA
0   23     9
1   21     8
2   22     7

In [89]:
#1. Filter the Age >22
df[df['Age']>22]

Name  Age Gender State  CGPA
0  kevin   23      m    TN     9

In [92]:
#4.names starts with j

str_j=df[df['Name'].str.startswith('j')]
#names_starting_with_j = df[df['Name'].str.startswith('j', case=False)]
print("\n. Names starting with 'j':")
print(str_j)


. Names starting with 'j':
   Name  Age Gender State  CGPA
1  john   21      m    KL     8


In [94]:
# 5.names contains 'n'
str_n=df[df['Name'].str.contains('n')]
print(str_n)

    Name  Age Gender State  CGPA
0  kevin   23      m    TN     9
1   john   21      m    KL     8


In [97]:
dfr1=pd.DataFrame({'Id':[1,2,3,5,9],
                    'Col1':[1,2,3,4,5],
                     'col2':[6,7,8,9,10],
                      'col4':['apple','orange','banana','strawberry','rasberry']})
dfr1

Id  Col1  col2        col4
0   1     1     6       apple
1   2     2     7      orange
2   3     3     8      banana
3   5     4     9  strawberry
4   9     5    10    rasberry

In [98]:
dfr2=pd.DataFrame({'Id':[1,1,3,5],
                    'ColA':[8,9,10,11],
                     'colB':[12,13,15,17],
                      'col4':['apple','orange','banana','kiwi']})
dfr2

Id  ColA  colB    col4
0   1     8    12   apple
1   1     9    13  orange
2   3    10    15  banana
3   5    11    17    kiwi

In [102]:
# Perform left join
left_join = pd.merge(dfr1, dfr2, on='Id', how='left')
print(f"Left Join:\n {left_join}")

# Perform right join
right_join = pd.merge(dfr1, dfr2, on='Id', how='right')
print(f"Right Join:\n {right_join}")

# Perform inner join
inner_join = pd.merge(dfr1, dfr2, on='Id', how='inner')
print(f"Inner Join:\n {inner_join}")

Left Join:
    Id  Col1  col2      col4_x  ColA  colB  col4_y
0   1     1     6       apple   8.0  12.0   apple
1   1     1     6       apple   9.0  13.0  orange
2   2     2     7      orange   NaN   NaN     NaN
3   3     3     8      banana  10.0  15.0  banana
4   5     4     9  strawberry  11.0  17.0    kiwi
5   9     5    10    rasberry   NaN   NaN     NaN
Right Join:
    Id  Col1  col2      col4_x  ColA  colB  col4_y
0   1     1     6       apple     8    12   apple
1   1     1     6       apple     9    13  orange
2   3     3     8      banana    10    15  banana
3   5     4     9  strawberry    11    17    kiwi
Inner Join:
    Id  Col1  col2      col4_x  ColA  colB  col4_y
0   1     1     6       apple     8    12   apple
1   1     1     6       apple     9    13  orange
2   3     3     8      banana    10    15  banana
3   5     4     9  strawberry    11    17    kiwi


In [103]:
# 1. Define sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 2. Create a NumPy array
array_for_sigmoid = np.array([2, 5, 6])

# 3. Apply the sigmoid function to the array
result = sigmoid(array_for_sigmoid)

# Print the result
print("Original array:", array_for_sigmoid)
print("Result after applying sigmoid function:", result)

Original array: [2 5 6]
Result after applying sigmoid function: [0.88079708 0.99330715 0.99752738]
