In [1]:
import numpy as np

In [2]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [3]:
input_vector = np.array([1,2,3])
hidden_state = np.array([4,5,6])

In [4]:
weights = {
    'Wi': np.array([[1,1,1,1,1,1],[2,2,2,2,2,2],[3,3,3,3,3,3]]).T,
    'Wf': np.array([[0,0,0,0,0,-1],[5,6,7,8,9,10],[3,4,5,6,7,8]]).T,
    'Wo': None,
    'Wc': np.array([[1,1,1,1,1,1],[2,2,2,2,2,2],[-3,-3,-3,-3,-3,-3]]).T,
    'bi': np.array([1,1,1]),
    'bf': np.array([1,2,3]),
    'bo': None,
    'bc': np.array([1,1,1]),
}

In [5]:
cell_state = np.array([5,5,5])

In [6]:
# Concatenate input and previous hidden state
combined = np.concatenate((input_vector, hidden_state))
print(combined)

[1 2 3 4 5 6]


In [7]:
# Input gate
i_t = sigmoid(np.dot(combined, weights['Wi']) + weights['bi'])
print(i_t)

[1. 1. 1.]


In [8]:
# Forget gate
f_t = sigmoid(np.dot(combined, weights['Wf']) + weights['bf'])
print(f_t)

[0.00669285 1.         1.        ]


In [9]:
# Output gate
# o_t = sigmoid(np.dot(combined, weights['Wo']) + weights['bo'])
o_t = np.array([0,0.5,1])

In [10]:
# Cell update
g_t = np.tanh(np.dot(combined, weights['Wc']) + weights['bc'])
print(g_t)

[ 1.  1. -1.]


In [11]:
# Update cell state
cell_state = f_t * cell_state + i_t * g_t
print(cell_state)

[1.03346425 6.         4.        ]


In [12]:
# Hidden state
hidden_state = o_t * np.tanh(cell_state)
print(hidden_state)

[0.         0.49999386 0.9993293 ]
