In [ ]:
# Instructor Notebook: TensorFlow Basics and Data Structures

# Install TensorFlow
# !pip install tensorflow

import tensorflow as tf
import numpy as np







## **Tensors**

**Definition:** Tensor the primary data structure in TensorFlow. A tensor is a generalization of vectors and matrices to potentially higher dimensions.

### **Types of Tensors:**

  

*  **Rank-0 Tensor (Scalar)**: A single number, e.g., 4.
*  **Rank-1 Tensor (Vector)**: A 1-D array of numbers, e.g., [1, 2, 3]

*  **Rank-2 Tensor (Matrix)**: A 2-D array of numbers, e.g., [[1, 2], [3, 4]].

* **Higher-Rank Tensors:** Tensors with more dimensions, e.g., a 3-D tensor representing a batch of images.

# Variables

Variables are special types of tensors used to store model parameters. They can be modified by the operations in the graph.

Usage: tf.Variable(initial_value)

# Constants

Definition: Tensors with a fixed value. Unlike variables, they cannot be modified.

Usage: tf.constant(value)

# Sparse Tensors
Definition: Efficient representation of tensors with a large proportion of zero values.

Usage: tf.sparse.SparseTensor(indices, values, dense_shape)

# Datasets

Definition: A powerful abstraction for handling input data. It provides an easy and efficient way to load and preprocess data.

Usage: tf.data.Dataset

### Common Methods:

tf.data.Dataset.from_tensor_slices(tensors)

dataset.map(function)

dataset.batch(batch_size)

dataset.shuffle(buffer_size)

In [ ]:

# Section 1: Tensors


# Creating different ranks of tensors
scalar = tf.constant(42)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [ ]:
# print("Scalar (Rank-0):", scalar)
print("Vector (Rank-1):", vector)
# print("Matrix (Rank-2):\n", matrix)
# print("3D Tensor (Rank-3):\n", tensor_3d)
# print("\n")

Vector (Rank-1): tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
# Section 2: Variables

# Creating variables
var = tf.Variable([1, 2, 3])
print("Variable:", var)
print("\n")

# Modifying variables
var.assign([4, 5, 6])
print("Modified Variable:", var)
print("\n")

var.assign_add([1, 1, 1])
print("Variable after assign_add:", var)
print("\n")

Variable: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


Modified Variable: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


Variable after assign_add: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 6, 7], dtype=int32)>




In [ ]:

# Section 3: Constants

# Creating constants
const = tf.constant([1, 2, 3])
print("Constant:", const)
print("\n")

Constant: tf.Tensor([1 2 3], shape=(3,), dtype=int32)




In [ ]:

# Section 4: Sparse Tensors

# Creating sparse tensors
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
print("Sparse Tensor:\n", sparse_tensor)

# Converting sparse tensor to dense
dense_tensor = tf.sparse.to_dense(sparse_tensor)
print("Dense Tensor:\n", dense_tensor)
print("\n")

Sparse Tensor:
 SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
Dense Tensor:
 tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)




In [ ]:
# Section 5: Datasets


# Creating a dataset from tensor slices
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
# print("Dataset:", dataset)

# Applying transformations
dataset = dataset.map(lambda x: x * 2)
dataset = dataset.batch(2)
dataset = dataset.shuffle(buffer_size=3)

print("Transformed Dataset:")
for batch in dataset:
    print(batch.numpy())
print("\n")


Transformed Dataset:
[6 8]
[2 4]
[10]




In [ ]:
# Section 6: Example Code for Students


# Task: Creating and Printing Tensors
rank1_tensor = tf.constant([10, 20, 30])
rank2_tensor = tf.constant([[1, 2], [3, 4]])

print("Rank-1 Tensor (Vector):", rank1_tensor)
print("Rank-2 Tensor (Matrix):\n", rank2_tensor)


Rank-1 Tensor (Vector): tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Rank-2 Tensor (Matrix):
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:

# Task: Performing Tensor Operations
tensor_addition = tf.add(rank1_tensor, [1, 2, 3])
tensor_multiplication = tf.multiply(rank2_tensor, 2)

print("Tensor Addition:", tensor_addition)
print("Tensor Multiplication:\n", tensor_multiplication)

Tensor Addition: tf.Tensor([11 22 33], shape=(3,), dtype=int32)
Tensor Multiplication:
 tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


In [ ]:
# Task: Creating and Modifying Variables
variable_tensor = tf.Variable([5, 10, 15])
variable_tensor.assign_add([1, 1, 1])

print("Modified Variable Tensor:", variable_tensor)

Modified Variable Tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 6, 11, 16], dtype=int32)>


In [ ]:
# Task: Working with Datasets
sample_dataset = tf.data.Dataset.from_tensor_slices([10, 20, 30, 40, 50])
sample_dataset = sample_dataset.map(lambda x: x - 5)
sample_dataset = sample_dataset.batch(3)
sample_dataset = sample_dataset.shuffle(buffer_size=2)

print("Iterating through the sample dataset:")
for batch in sample_dataset:
    print(batch.numpy())

Iterating through the sample dataset:
[35 45]
[ 5 15 25]
